spring:
  application:
    name: search-service
  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://postgres:5435/searchdb
    username: search
    password: searchpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8100