

services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres

  reservation-service:
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
      - kafka

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - config-server
      - discovery-service
      - kafka

  booking-composition-service:
    build:
      context: .
      dockerfile: booking-composition-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres