version: '3.8'

services:
  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-server

  hotel-service:
    build:
      context: ./hotel-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
      - postgres

  reservation-service:
    build:
      context: ./reservation-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
      - postgres
      - kafka

  search-service:
    build:
      context: ./search-service
    ports:
      - "8100:8100"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
      - postgres

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8085:8080"
    depends_on:
      - config-server
      - discovery-server
      - kafka

  booking-composition-service:
    build:
      context: ./booking-composition-service
    ports:
      - "8086:8086"
    depends_on:
      - config-server
      - discovery-server
      - api-gateway
      - postgres