services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,native

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  reservation-service:
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - config-server
      - discovery-service
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  booking-composition-service:
    build:
      context: .
      dockerfile: booking-composition-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev