services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,native

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  reservation-service:
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - config-server
      - discovery-service
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  booking-composition-service:
    build:
      context: .
      dockerfile: booking-composition-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - config-server
      - discovery-service
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartbooking

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"