services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - booking-net

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - booking-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev,native
    networks:
      - booking-net

  reservation-service:
    build:
      context: .
      dockerfile: reservation-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - booking-net

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - booking-net

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - booking-net

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - config-server
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - booking-net
networks:
  booking-net:
    external: true