version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: smart-booking-db
    environment:
      POSTGRES_DB: smart_booking
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: