version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: smart-keycloak
    ports:
      - "8060:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev