server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://smart-keycloak:8080/realms/smart-booking

  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/rooms/**

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

        - id: booking-composition-service
          uri: lb://BOOKING-COMPOSITION-SERVICE
          predicates:
            - Path=/compose/**

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG