server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/rooms/**

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
        - id: booking-composition-service
          uri: http://localhost:8090
          predicates:
            - Path=/compose/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka