spring:
  application:
    name: hotel-service
  profiles:
    active: local

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_booking
    username: booking_user
    password: booking_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

hotel:
  welcome-message: "Welcome to Smart Booking Hotel Service-runtime test-2"