FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

COPY . .
WORKDIR /app/discovery-service
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

COPY --from=build /app/discovery-service/target/*.jar app.jar

EXPOSE 8761

ENTRYPOINT ["java", "-jar", "app.jar"]