spring:
  application:
    name: reservation-service
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_booking
    username: booking_user
    password: booking_pass
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

client:
  room-service:
    url: http://localhost:8080
  hotel-service:
    url: http://localhost:8080

server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka