server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/lutfiusluer/development/projects/smart-booking-system/config-server/src/main/resources/config-repo


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka